services:
  postgres:
    image: postgres:17-alpine
    container_name: accounting-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pass@123
      POSTGRES_DB: accounting_dev
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - accounting-network
    shm_size: 128mb

  accounting.api:
    image: ${DOCKER_REGISTRY-}accountingapi
    build:
      context: .
      dockerfile: src/Accounting.API/Dockerfile

volumes:
  postgres-data:

networks:
  accounting-network:
    driver: bridge
